import NavMenu from "@/components/NavMenu";
import SessionProvider from "@/components/SessionProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import { auth } from "../libs/authconfig";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await auth();
    return (
        <html lang="en">
            <body
                style={{
                    backgroundImage: 'url("/bbblurry.svg")',
                    backgroundSize: "cover",
                }}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem
                    disableTransitionOnChange
                >
                    <SessionProvider session={session}>
                        <main className="@container mx-auto max-w-7xl gap-2 p-4 space-y-4">
                            <NavMenu />
                            {children}
                        </main>
                    </SessionProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
