import NavMenu from "@/components/NavMenu";
import SessionProvider from "@/components/SessionProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import { auth } from "../libs/authconfig";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await auth();
    return (
        <html lang="en">
            <SessionProvider session={session}>
                <body className="w-full overflow-x-hidden">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="light"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <NavMenu />
                        <main className="@container gap-2 min-h-screen m-large">
                            {children}
                        </main>
                    </ThemeProvider>
                </body>
            </SessionProvider>
        </html>
    );
}
