import Container from "@/components/container";
import { SideBar } from "./components/side-bar";

import { type Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function AdminLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <Container
            className="flex @container"
            as="section"
            width="wide"
            height="page"
        >
            <SideBar />

            <section className="flex-1">{children}</section>
        </Container>
    );
}
